### ISSUE TITLE
{prefix}servers and {prefix}server id 

### ISSUE THREAD

**Issue by Justsomeguy798** [Pogy-Bot/Pogy#3]
error code is 

  {prefix}servers
**message.client.guilds.cache.array is not a function
    at module.exports.run  (/home/runner/boltza/src/commands/owner/servers.js:16:49)
    at module.exports.runCommand (/home/runner/boltza/src/events/message/messageCreate.js:307:19)
    at module.exports.run (/home/runner/boltza/src/events/message/messageCreate.js:281:20)** 
    
    
    
    {prefix}server id 

has a different error 

**Cannot read properties of undefined (reading 'user')**

**Comment by peterhanania** [comment]
fixed in https://github.com/Pogy-Bot/Pogy/commit/9dfca80a74fee2289ad17f201e511c3a27d1da4c

I recommend you delete your old src folder and update.
