### ISSUE TITLE
I cannot start the bot

### ISSUE THREAD

**Issue by DisPaisy** [Pogy-Bot/Pogy#43]
I'm using CentOS 7 with node.js version 16.20.1

```
2023-08-08 20:26:20 [info] [ERROR] [unhandledRejection] /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/ds-bot-priv/Pogy/node_modules/canvas/build/Release/canvas.node)
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/ds-bot-priv/Pogy/node_modules/canvas/build/Release/canvas.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/root/ds-bot-priv/Pogy/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/root/ds-bot-priv/Pogy/node_modules/canvas/lib/canvas.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32) {
  code: 'ERR_DLOPEN_FAILED'
} Promise {
  <rejected> Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/ds-bot-priv/Pogy/node_modules/canvas/build/Release/canvas.node)
      at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
      at Module.load (node:internal/modules/cjs/loader:1076:32)
      at Function.Module._load (node:internal/modules/cjs/loader:911:12)
      at Module.require (node:internal/modules/cjs/loader:1100:19)
      at require (node:internal/modules/cjs/helpers:108:18)
      at Object.<anonymous> (/root/ds-bot-priv/Pogy/node_modules/canvas/lib/bindings.js:3:18)
      at Module._compile (node:internal/modules/cjs/loader:1198:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
      at Module.load (node:internal/modules/cjs/loader:1076:32)
      at Function.Module._load (node:internal/modules/cjs/loader:911:12)
      at Module.require (node:internal/modules/cjs/loader:1100:19)
      at require (node:internal/modules/cjs/helpers:108:18)
      at Object.<anonymous> (/root/ds-bot-priv/Pogy/node_modules/canvas/lib/canvas.js:9:18)
      at Module._compile (node:internal/modules/cjs/loader:1198:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
      at Module.load (node:internal/modules/cjs/loader:1076:32) {
    code: 'ERR_DLOPEN_FAILED'
  }
}
Segmentation fault
```

**Comment by lndmanh** [comment]
Try following this comment, he wrote detailed instructions for your problem.
https://github.com/Automattic/node-canvas/issues/1796#issuecomment-1253159308

**Comment by DisPaisy** [comment]
ok, thanks
