### ISSUE TITLE
slash commands

### ISSUE THREAD

**Issue by XceptDev** [Pogy-Bot/Pogy#54]
2024-02-24 13:16:55 [info] [ERROR] [multipleResolves] MULTIPLE RESOLVES
resolve Promise {
  {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { application_id: [Object] }
  }
} undefined
DiscordAPIError[50035]: Invalid Form Body
application_id[NUMBER_TYPE_COERCE]: Value "commands" is not snowflake.
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:722:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1120:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:953:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1266:22) {
  requestBody: {
    files: undefined,
    json: [
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object],
      [Object], [Object]
    ]
  },
  rawError: {
    message: 'Invalid Form Body',
    code: 50035,
    errors: { application_id: [Object] }
  },
  code: 50035,
  status: 400,
  method: 'PUT',
  url: 'https://discord.com/api/v9/applications//commands'
}

**Comment by azaresw** [comment]
U forgot clientid
